=== pedrobrnpng/factory-floor-management-isep-lapr4/Central System/eapli-base/xml/1180712/1180712.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
    <xsd:element name="SSFM" type="TFactoryFloor">
        <xsd:key name="RawMaterialCategoryKey">
            <xsd:selector xpath="RawMaterialCategories/RawMaterialCategory"/>
            <xsd:field xpath="@name"/>
        </xsd:key>
        <xsd:key name="RawMaterialKey">
            <xsd:selector xpath="RawMaterials/RawMaterial"/>
            <xsd:field xpath="@internalCode"/>   
        </xsd:key>
        <xsd:keyref name="RawMaterialRefKey" refer="RawMaterialCategoryKey">
            <xsd:selector xpath="RawMaterials/RawMaterial"/>
            <xsd:field xpath="@nameRawMaterialCategory"/>   
        </xsd:keyref>
        <xsd:keyref name="ConsumptionRawMaterialRefKey" refer="RawMaterialKey">
            <xsd:selector xpath="Consumptions/Consumption"/>
            <xsd:field xpath="@product"/>   
        </xsd:keyref>
        <xsd:keyref name="RawMaterialGlobalRefKey" refer="RawMaterialKey">
            <xsd:selector xpath="Consumptions/EffectiveConsumptions/Product"/>
            <xsd:field xpath="@id"/>   
        </xsd:keyref>
		<xsd:keyref name="RealConsumptionProductRefKey" refer="RawMaterialKey">
			<xsd:selector xpath="Consumptions/RealConsumptions/Consumption"/>
            <xsd:field xpath="@product"/>   
        </xsd:keyref>
                
        <!-- These elements are represented by other members of the group, so this part should be commented here to be able to test -->
        <!--<xsd:keyref name="ConsumptionDepositRefKey" refer="DepositKey">
            <xsd:selector xpath="Consumptions/EffectiveConsumptions/Consumption"/>
            <xsd:field xpath="@deposit"/>   
        </xsd:keyref>
		<xsd:keyref name="MachineRefKey" refer="MachineKey">
            <xsd:selector xpath="Consumptions/EffectiveConsumptions/Consumption"/>
            <xsd:field xpath="@machine"/>   
        </xsd:keyref>
        <xsd:keyref name="ConsumptionProductRefKey" refer="ProductKey">
            <xsd:selector xpath="Consumptions/EffectiveConsumptions/Consumption"/>
            <xsd:field xpath="@product"/>   
        </xsd:keyref>
		<xsd:keyref name="ProductRefKey" refer="ProductKey">
			<xsd:selector xpath="Consumptions/EffectiveConsumptions/Product"/>
			<xsd:field xpath="@id"/>
		</xsd:keyref>
        <xsd:keyref name="DepositRefKey" refer="DepositKey">
            <xsd:selector xpath="Consumptions/EffectiveConsumptions/Deposit"/>
            <xsd:field xpath="@id"/>   
        </xsd:keyref>
		<xsd:keyref name="RealConsumptionProductRefKey" refer="ProductKey">
			<xsd:selector xpath="Consumptions/RealConsumptions/Consumption"/>
            <xsd:field xpath="@product"/>   
        </xsd:keyref>-->
    </xsd:element>

    <!-- General -->		
    <xsd:complexType name="TFactoryFloor">
        <xsd:sequence>
            <xsd:element name="RawMaterialCategories" type="TRawMaterialCategories" minOccurs="0"/>
            <xsd:element name="RawMaterials" type="TRawMaterials" minOccurs="0"/>
            <xsd:element name="Consumptions" type="TConsumptions" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
	
	<xsd:simpleType name="TInternalCode">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="15"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="TQuantity">
		<xsd:restriction base="xsd:int">
			<xsd:minExclusive value="0"/>
		</xsd:restriction>
	</xsd:simpleType>

    <!-- Raw Material Categories -->
    <xsd:complexType name="TRawMaterialCategories">
        <xsd:sequence>
            <xsd:element name="RawMaterialCategory" type="TRawMaterialCategory" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="TRawMaterialCategory">
        <xsd:sequence>
            <xsd:element name="description" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="TRawMaterialCategoryName" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="TRawMaterialCategoryName">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="10"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Raw Materials -->
     <xsd:complexType name="TRawMaterials">
        <xsd:sequence>
            <xsd:element name="RawMaterial" type="TRawMaterial" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="TRawMaterial">
        <xsd:sequence>
            <xsd:element name="description" type="xsd:string"/>
			<xsd:element name="TechnicalSheet" type="TTechnicalSheet"/>
        </xsd:sequence>
        <xsd:attribute name="internalCode" type="TInternalCode" use="required"/>
        <xsd:attribute name="nameRawMaterialCategory" type="TRawMaterialCategoryName" use="required"/>
    </xsd:complexType>
	
	<xsd:complexType name="TTechnicalSheet">
		<xsd:sequence>
			<xsd:element name="nameTechnicalSheet" type="xsd:string"/> 
		</xsd:sequence>
	</xsd:complexType>
	
    <!-- Comsumption -->
    <xsd:complexType name="TConsumptions">
        <xsd:sequence>
			<xsd:element name="EffectiveConsumptions" type="TEffectiveConsumptions"/>
			<xsd:element name="RealConsumptions" type="TRealConsumptions"/>
        </xsd:sequence>
    </xsd:complexType>
	
	<xsd:complexType name="TEffectiveConsumptions">
		<xsd:sequence>
			<xsd:element name="Consumption" type="TEffectiveConsumption" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
    
    <xsd:complexType name="TEffectiveConsumption">
        <xsd:sequence>
            <xsd:element name="quantity" type="xsd:int"/>
        </xsd:sequence>
        <xsd:attribute name="machine" type="xsd:string" use="required"/>
        <xsd:attribute name="product" type="TInternalCode" use="optional"/>
		<xsd:attribute name="rawMaterial" type="TInternalCode" use="optional"/>
        <xsd:attribute name="deposit" type="TInternalCode" use="optional"/>
    </xsd:complexType>
	
	<xsd:complexType name="TRealConsumptions">
		<xsd:sequence>
			<xsd:element name="Deposit" type="TDepositConsumption" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="RawMaterial" type="TRawMaterialConsumption" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Product" type="TProductConsumption" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="TDepositConsumption">
        <xsd:sequence>
            <xsd:element name="quantity" type="TQuantity"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="TProductConsumption">
        <xsd:sequence>
            <xsd:element name="quantity" type="TQuantity"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>
	
	<xsd:complexType name="TRawMaterialConsumption">
		<xsd:sequence>
			<xsd:element name="quantity" type="TQuantity"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required"/>
	</xsd:complexType>
   
</xsd:schema>

=== pedrobrnpng/factory-floor-management-isep-lapr4/Central System/eapli-base/xml/1180712/1180712.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<SSFM
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='1180712.xsd'>
    <RawMaterialCategories>
		<RawMaterialCategory name="cat1">
			<description>Wood</description>
		</RawMaterialCategory>
		<RawMaterialCategory name="cat2">
			<description>Metal</description>
		</RawMaterialCategory>
	</RawMaterialCategories>

	<RawMaterials>
		<RawMaterial internalCode="rm1" nameRawMaterialCategory="cat1">
			<description>softwood</description>
			<TechnicalSheet>
				<nameTechnicalSheet>softwood.pdf</nameTechnicalSheet>
			</TechnicalSheet>
		</RawMaterial>
		<RawMaterial internalCode="rm2" nameRawMaterialCategory="cat1">
			<description>softwood</description>
			<TechnicalSheet>
				<nameTechnicalSheet>softwood.pdf</nameTechnicalSheet>
			</TechnicalSheet>
		</RawMaterial>
		<RawMaterial internalCode="rm3" nameRawMaterialCategory="cat2">
			<description>iron</description>
			<TechnicalSheet>
				<nameTechnicalSheet>iron.pdf</nameTechnicalSheet>
			</TechnicalSheet>
		</RawMaterial>
		<RawMaterial internalCode="rm4" nameRawMaterialCategory="cat2">
			<description>steel</description>
			<TechnicalSheet>
				<nameTechnicalSheet>steel.pdf</nameTechnicalSheet>
			</TechnicalSheet>
		</RawMaterial>
	</RawMaterials>
	
    <Consumptions>
		<EffectiveConsumptions>
			<Consumption machine="m1" deposit="d1" rawMaterial="rm1">
				<quantity>20</quantity>
			</Consumption>
			<Consumption machine="m2" deposit="d2" rawMaterial="rm2">
				<quantity>20</quantity>
			</Consumption>
			<Consumption machine="m2" deposit="d2" product="product3">
				<quantity>10</quantity>
			</Consumption>
			<Consumption machine="m2" deposit="d2" product="product2">
				<quantity>20</quantity>
			</Consumption>
		</EffectiveConsumptions>
		<RealConsumptions>
			<Deposit id="d1">
				<quantity>40</quantity>
			</Deposit>
			<Deposit id="d2">
				<quantity>30</quantity>
			</Deposit>
			<RawMaterial id="rm1">
				<quantity>20</quantity>
			</RawMaterial>
			<RawMaterial id="rm2">
				<quantity>20</quantity>
			</RawMaterial>
			<Product id="product3">
				<quantity>10</quantity>
			</Product>
			<Product id="product2">
				<quantity>20</quantity>
			</Product>
		</RealConsumptions>
	</Consumptions>

</SSFM>
